# Generated by Django 4.1.2 on 2023-05-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_saveforlater_id_alter_userrating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='book_thumbnails/')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
    ]
